In [ ]:
import numpy as np


In [ ]:
np.ones((2,1))


array([[1.],
       [1.]])

In [ ]:
np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a = np.array([1,2,3,4])
a.reshape(2, 2)


array([[1, 2],
       [3, 4]])

In [ ]:
np.ones((2,1))

array([[1.],
       [1.]])

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
o = np.ones((3,3))


In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
o = np.arange(0,10,2)


In [ ]:
o

array([0, 2, 4, 6, 8])

In [ ]:
a = np.array([[1,2], [3,4]])
print(a.shape)

(2, 2)


In [ ]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [ ]:
b = np.array([[1,2], [3,4]])
print(b.ndim)

2


In [ ]:
c = np.array([[1,2], [3,4]])
print(c.shape)

(2, 2)


In [ ]:
 a = np.array([[1,2], [3,4]])
 print(a.size)

4


In [ ]:
e = np.array([[1,2],
              [3,4]])
s = np.array([[2,3],
             [4,5]])
print(np.sum(e))
print(np.sum(s))

10
14


In [ ]:
e = np.array([[1,2], [3,4]])
print(e.dtype)

int64


In [ ]:
w = np.array([[1,2], [3,4]])
print(np.mean(w))


2.5


In [ ]:
print(np.max(w))
print(np.min(w))

4
1


In [ ]:
print(w.T)


[[1 3]
 [2 4]]


In [ ]:
s = np.array([4,2,3,1])
print(np.sort(s))

[1 2 3 4]
